env:
  - GO111MODULE=on
  - CGO_ENABLED=0

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
      - -v
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=GithubAction

universal_binaries:
  - replace: false

archives:
  - format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root

sboms:
  - artifacts: archive
